name: Android Release Build

on:
  push:
    branches: [ frontend-pipeline ]

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: cookimate-frontend/frontend/package-lock.json

      - name: Install dependencies
        working-directory: cookimate-frontend/frontend
        run: npm install --legacy-peer-deps

      - name: Decode Keystore
        run: |
          mkdir -p cookimate-frontend/frontend/android/app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > cookimate-frontend/frontend/android/app/release.keystore

      - name: Build Android Release
        working-directory: cookimate-frontend/frontend/android
        run: |
          chmod +x gradlew
          ./gradlew bundleRelease
          cp app/build/outputs/bundle/release/app-release.aab $GITHUB_WORKSPACE/app-release.aab
        env:
          ANDROID_KEYSTORE_PATH: "release.keystore"
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Verify file exists
        run: |
          ls -la ${{ github.workspace }}/app-release.aab

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cookimate-493709

      - name: Upload to Google Play
        run: |
          gcloud --quiet alpha play publishing upload \
            --package-name=com.cookimateLabs.cookimate \
            --aab=${{ github.workspace }}/app-release.aab \
            --track=internal